
Insert into BTO_LIMITCATEGORY (METADATA,LIMIT) values ('WORD_DROP','600');
Insert into BTO_LIMITCATEGORY (METADATA,LIMIT) values ('SUPER_GRID','300');
Insert into BTO_LIMITCATEGORY (METADATA,LIMIT) values ('WORD_RESCUE','600');
Insert into BTO_LIMITCATEGORY (METADATA,LIMIT) values ('MEMORY_MATCH','420');
Insert into BTO_LIMITCATEGORY (METADATA,LIMIT) values ('M03','720');
Insert into BTO_LIMITCATEGORY (METADATA,LIMIT) values ('M04','420');
Insert into BTO_LIMITCATEGORY (METADATA,LIMIT) values ('M05','420');
Insert into BTO_LIMITCATEGORY (METADATA,LIMIT) values ('M06','420');
Insert into BTO_LIMITCATEGORY (METADATA,LIMIT) values ('M07','420');