
Insert into BTO_SUBNIVEL (SUBNIVEL,NIVEL,HORAS,PRIORIDAD) values ('NOSUBLVL','NOLVL','30','0');
Insert into BTO_SUBNIVEL (SUBNIVEL,NIVEL,HORAS,PRIORIDAD) values ('PREA1.1','PREA1','30','1');
Insert into BTO_SUBNIVEL (SUBNIVEL,NIVEL,HORAS,PRIORIDAD) values ('PREA1.2','PREA1','30','2');
Insert into BTO_SUBNIVEL (SUBNIVEL,NIVEL,HORAS,PRIORIDAD) values ('PREA1.3','PREA1','30','3');
Insert into BTO_SUBNIVEL (SUBNIVEL,NIVEL,HORAS,PRIORIDAD) values ('A1.1','A1','30','4');
Insert into BTO_SUBNIVEL (SUBNIVEL,NIVEL,HORAS,PRIORIDAD) values ('A1.2','A1','30','5');
Insert into BTO_SUBNIVEL (SUBNIVEL,NIVEL,HORAS,PRIORIDAD) values ('A1.3','A1','90','6');
Insert into BTO_SUBNIVEL (SUBNIVEL,NIVEL,HORAS,PRIORIDAD) values ('A2.1','A2','90','7');
Insert into BTO_SUBNIVEL (SUBNIVEL,NIVEL,HORAS,PRIORIDAD) values ('A2.2','A2','90','8');
Insert into BTO_SUBNIVEL (SUBNIVEL,NIVEL,HORAS,PRIORIDAD) values (,'B1.1','B1','90','9');
Insert into BTO_SUBNIVEL (SUBNIVEL,NIVEL,HORAS,PRIORIDAD) values (,'B1.2','B1','90','10');
Insert into BTO_SUBNIVEL (SUBNIVEL,NIVEL,HORAS,PRIORIDAD) values (,'B1.3','B1','90','11');
