
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "DOCENTESREGISTRADOSVIEW" ("ID", "USUARIO_RESTFUL", "EMAIL", "CODIGO_SECRETARIA", "NOMBRE_SECRETARIA", "TIPO_DOCUMENTO", "NRO_DOCUMENTO", "NOMBRE_COMPLETO", "APELLIDO1", "APELLIDO2", "NOMBRE1", "NOMBRE2", "CODIGO_DANE_EST", "DANE_SEDE", "NOMBRE_ESTABLECIMIENTO", "NOMBRE_SEDE_EDUCATIVA", "CONFIRMADO") AS 
  SELECT
	ID,
	USUARIO_RESTFUL, 
	EMAIL, 
	CODIGO_SECRETARIA, 
	s.NOMBRE AS nombre_secretaria, 
	TIPO_DOCUMENTO, 
	NRO_DOCUMENTO, 
	NOMBRE1 || ' ' || NOMBRE2 || ' ' || ' ' || APELLIDO1 || ' ' || ' ' || APELLIDO2 as nombre_completo,
	APELLIDO1,
	APELLIDO2,
	NOMBRE1,
	NOMBRE2,
	CODIGO_DANE_EST,
	DANE_SEDE,
	NOMBRE_ESTABLECIMIENTO,
	NOMBRE_SEDE_EDUCATIVA,
	CONFIRMADO
FROM BTO_DOCENTE d, BTO_SECRETARIA s
WHERE d.CODIGO_SECRETARIA = s.CLAVE
AND USUARIO_RESTFUL IS NOT NULL;

